---
title: "Intro"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(spdep)
library(tigris)
library(acs)
library(tidyverse)
library(tmap)
library(tidycensus)
library(yaImpute)
library(spBayes)
library(MBA)
library(fields)
library(rgdal)
library(RgoogleMaps)
library(raster)
library(coda)
library(geoR)
library(leaps)
library(MASS)
library(knitr)
library(plotly) 
```

#Description of data set when it's set
description

#Research Questions
questions

#Exploration
```{r}


api="fd79d3eb4ce2c69f2ca5d2ac69199b3930b798ed"
api.key.install(key=api)
acs.tables.install()
set.seed(1234) # because we are randomizing part of the process

# Access the shapefile
s <- get_acs(key = api, geography = "tract", variables = "B19013_001",
             state = c("VA"), geometry = TRUE)

# remove NA values is any
s <- na.omit(s)

# select column to work with
s <- subset(s, select=c("estimate"))

# check data skewness
hist(s$estimate, main=NULL)

# check for outliers
boxplot(s$estimate, horizontal = TRUE)

# plot variable
tm_shape(s) + tm_fill(col="estimate", style="quantile", n=5, palette="Greens") +
  tm_legend(outside=TRUE)
```

#Model Fitting
```{r}
s2 <- s %>% separate(NAME, c("Tract", "County", "State"), sep = "[,]") %>%
  separate(County, c(NA, "County"), sep = "[ ]")
data <- data %>% separate(county, c("County", NA), sep = "[ ]")
s2 <- inner_join(s2, data, by = "County")
s3 <- subset(s, select=c("estimate"))
RepPred <- subset(s2, select = c("County", "State", "geometry", "estimate", "moe", "cand", "pct", "st")) %>% 
  filter(cand == "Donald Trump")

#Do predictions and model fitting on only republican percentage
ns = nrow(RepPred)
coords = RepPred[,3]
y_list = as.matrix(RepPred[,7])
x = as.matrix(RepPred[,4:5])

set.seed(1)
ncoords <- nrow(coords)
coordsIndx <- sample(1:ns, 0.75*ns)
coords.train <- coords[coordsIndx, ]
coords.test <- coords[-coordsIndx, ]
y.train <- y_list[coordsIndx, ]
y.test <- y_list[-coordsIndx, ]
x.train <- x[coordsIndx, ]
x.test <- x[-coordsIndx, ]
max.dist =  0.5 * max(iDist(coords)) 

nc.sids <- readOGR(system.file("shapes/sids.shp", package="spData")[1], verbose = FALSE) 
proj4string(nc.sids) <- CRS("+proj=longlat +ellps=clrk66") 

library(maps) 
library(maptools) 
map.text("county", "nebraska", fill = FALSE, plot = TRUE, cex = 0.5)
UScounties = as.data.frame(map("county", fill = TRUE, plot = FALSE))
county.ID <- sapply(strsplit(UScounties$names, ","), function(x) x[2]) %>% unique()
USPoly = map2SpatialPolygons(UScounties, IDs=county.ID)
ne.nb = poly2nb(ne.poly) 
ne.adj.mat = nb2mat(ne.nb, style="B") 

#find neighbors of Lancaster county in Nebraska 
ne.region.id <- attr(ne.nb, "region.id") 
lancaster.neighbors.index = ne.nb[[match("lancaster", ne.region.id)]] 
lancaster.neighbors = rownames(ne.adj.mat[lancaster.neighbors.index,]) 
lancaster.neighbors
```

#Cross-Validation

#Predictions

#Results

